FROM node:18 AS builder

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --omit=dev --verbose

COPY . .

RUN npm run build

FROM nginx:alpine AS nginx

# Copy the NGINX configuration
COPY ./nginx.conf /etc/nginx/nginx.conf

# Copy built Next.js files to NGINX
COPY --from=builder /usr/src/app/.next /usr/share/nginx/html/.next/
COPY --from=builder /usr/src/app/public /usr/share/nginx/html/public/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]