# Build Stage
FROM node:18 AS builder

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --only=production

COPY . .

RUN npm run build

FROM nginx:alpine
# FROM nginx:alpine AS nginx

# Copy the NGINX configuration
COPY ./nginx.conf /etc/nginx/nginx.conf

# Copy built Next.js files to NGINX
COPY --from=builder /usr/src/app/.next /usr/share/nginx/html/.next/
COPY --from=builder /usr/src/app/public /usr/share/nginx/html/public/

# COPY --from=builder /usr/src/app/next.config.js /usr/share/nginx/html/next.config.js
# COPY --from=builder /usr/src/app/package.json /usr/share/nginx/html/package.json

# FROM node:18 AS runner

# WORKDIR /usr/src/app

# COPY --from=builder /usr/src/app ./

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]