version: '3.8'

services:
  client:
    container_name: music-app-client-prod
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - '3024:3000'
    environment:
      NEXT_PUBLIC_API_URL: http://server:5000
    depends_on:
      - server
    # pull_policy: build

  server:
    container_name: music-app-server-prod
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - '5000:5000'
    env_file:
      - .env
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5000/health"]      
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres
    container_name: music-app-postgres-prod
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: music-app-prod
      POSTGRES_USER: user-name
      POSTGRES_PASSWORD: strong-password
      PGDATA: /var/lib/postgresql/data/music-app-prod
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: music-app-pgadmin-prod
    restart: always
    ports:
      - '8888:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data:
