FROM node:20-alpine as builder

ENV NODE_ENV build

USER node
WORKDIR /usr/src/app

COPY package*.json ./
RUN npm ci

COPY prisma ./prisma
COPY --chown=node:node . .

RUN npx prisma generate \
    && npm run build \
    && npm prune --omit=dev

# ---

FROM node:20-alpine

ENV NODE_ENV production

USER node
WORKDIR /usr/src/app

# COPY --from=builder --chown=node:node /usr/src/app/package*.json ./
# COPY --from=builder --chown=node:node /usr/src/app/node_modules/ ./node_modules/
# COPY --from=builder --chown=node:node /usr/src/app/dist/ ./dist/
# COPY --from=builder --chown=node:node /usr/src/app/prisma ./prisma
COPY --from=builder /usr/src/app .

CMD [  "npm", "run", "start:prod" ]

