# Stage 1: Build the NestJS app
FROM node:18 AS builder

WORKDIR /usr/src/main

# Install build tools for native modules
RUN apt-get update && apt-get install -y \
    build-essential \
    python3 \
    && rm -rf /var/lib/apt/lists/*

# Install dependencies
COPY package*.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Rebuild bcrypt from source
RUN npm rebuild bcrypt --build-from-source

# Generate Prisma Client
COPY prisma ./prisma
RUN npx prisma generate

# Copy application files and build the NestJS app
COPY . .
RUN npm run build

# Stage 2: Run the app in production mode
FROM node:18-alpine AS runner

WORKDIR /usr/src/main

# Copy the built files and necessary resources from the previous stage
COPY --from=builder /usr/src/main/dist ./dist
COPY --from=builder /usr/src/main/node_modules ./node_modules
COPY --from=builder /usr/src/main/package.json ./package.json

EXPOSE 5000

# Run the application in production mode
CMD ["npm", "run", "start:prod"]
