FROM node:18 AS builder

WORKDIR /usr/src/main

COPY package*.json ./

RUN npm install --omit=dev --verbose

COPY . .

RUN npx prisma generate

RUN npm run build

FROM nginx:alpine AS nginx

COPY ./nginx.conf /etc/nginx/nginx.conf

FROM node:18 AS runner

COPY --from=builder /usr/src/app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]