#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo coucou
cd client && npm run lint && npm run format && cd .. && cd server && npm audit
# cd client && npm run lint && cd ../server && npm audit
